graphics:
  antialiasing-level: 4
  vsync-enabled: yes
  hide-cursor: yes

controls:
  keyboard-mapping:
    pause: esc
    weapon: z
    aim: x
  gamepads:
    - name: SonyPS3Controller
      vendor-id: 1356
      product-id: 616
      button-mapping:
        pause: 16
        weapon: 11
        aim: 10
    - name: SonyPS4Controller
      vendor-id: 1356
      product-id: 1476
      button-mapping:
        pause: 9
        weapon: 6
        aim: 7

localization:
  strings:
    app-name: FLIGHT
