graphics:
  antialiasing-level: 4
  vsync-enabled: yes
  hide-cursor: yes

controls:
  keyboard-mapping:
    pause: esc
    weapon: z
  joysticks:
    - name: SonyPS3Controller
      vendor-id: 1356
      product-id: 616
      button-mapping:
        pause: 16
        weapon: 11
    - name: SonyPS4Controller
      vendor-id: 1356
      product-id: 1476
      button-mapping:
        pause: 12
        weapon: 5

localization:
  strings:
    app-name: FLIGHT
